# Generated by Django 2.0.5 on 2018-05-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MindState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('anger', models.PositiveIntegerField()),
                ('attitude', models.PositiveIntegerField()),
                ('appearance', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SelfEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('self_value', models.PositiveIntegerField()),
                ('parent_value', models.PositiveIntegerField()),
                ('friend_value', models.PositiveIntegerField()),
            ],
        ),
    ]
