# Generated by Django 2.0.7 on 2018-08-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MindState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('anger', models.CharField(max_length=50)),
                ('attitude', models.CharField(max_length=50)),
                ('appearance', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SelfEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('self_value', models.CharField(max_length=50)),
                ('parent_value', models.CharField(max_length=50)),
                ('friend_value', models.CharField(max_length=50)),
            ],
        ),
    ]
