# -*- coding: utf-8 -*-
from .base import *

ALLOWED_HOSTS = ['*']

# SSL (HTTPS) SETUP
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
SECURE_SSL_REDIRECT = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SECURE_HSTS_SECONDS = 10
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

SECRET_KEY = '1x7w9-)9+tb)ns@az%sng+vl8n132p^w5=qauz#7x@@nvs9(n8'