# Generated by Django 2.0.5 on 2018-06-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePlay', '0003_auto_20180601_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gonogo',
            name='comission_Error',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='gonogo',
            name='omission_Error',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='gonogo',
            name='success',
            field=models.PositiveIntegerField(),
        ),
    ]
