# Generated by Django 2.0.5 on 2018-06-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePlay', '0004_auto_20180601_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gonogo',
            name='comission_Error',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gonogo',
            name='omission_Error',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gonogo',
            name='success',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
