# Generated by Django 2.0.5 on 2018-06-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePlay', '0006_auto_20180601_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gonogo',
            name='comission_Error',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gonogo',
            name='gonogoNumber',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gonogo',
            name='omission_Error',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gonogo',
            name='stage',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gonogo',
            name='success',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nback',
            name='stage',
            field=models.CharField(max_length=50),
        ),
    ]
