# Generated by Django 2.0.4 on 2018-05-16 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balloon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.CharField(max_length=50)),
                ('rt', models.FloatField(default=-1.0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.BalloonScore')),
            ],
        ),
        migrations.RemoveField(
            model_name='balloontext',
            name='bs',
        ),
        migrations.RemoveField(
            model_name='balloontext',
            name='date',
        ),
        migrations.RemoveField(
            model_name='balloontext',
            name='rt',
        ),
        migrations.AlterField(
            model_name='balloontext',
            name='txt',
            field=models.CharField(max_length=50),
        ),
    ]
