# Generated by Django 2.0.4 on 2018-05-17 22:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_stroopscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardsortStimulus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rt', models.FloatField(default=-1.0)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('cs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.CardsortScore')),
            ],
        ),
        migrations.CreateModel(
            name='DigitNbackStimulus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rt', models.FloatField(default=-1.0)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('ds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.DigitNbackScore')),
            ],
        ),
        migrations.CreateModel(
            name='GonogoStimulus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rt', models.FloatField(default=-1.0)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('gs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.GonogoScore')),
            ],
        ),
        migrations.CreateModel(
            name='ImageNbackStimulus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rt', models.FloatField(default=-1.0)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('ims', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.DigitNbackScore')),
            ],
        ),
        migrations.CreateModel(
            name='StroopStimulus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rt', models.FloatField(default=-1.0)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('ss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.DigitNbackScore')),
            ],
        ),
        migrations.RenameField(
            model_name='balloon',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='balloon',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
