# Generated by Django 2.0.4 on 2018-05-18 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20180518_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenbackstimulus',
            name='ims',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.ImageNbackScore'),
        ),
        migrations.AlterField(
            model_name='stroopstimulus',
            name='ss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.StroopScore'),
        ),
    ]
