# Generated by Django 2.0.5 on 2018-05-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20180518_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='balloon',
            name='response',
            field=models.IntegerField(default=0),
        ),
    ]
