# Generated by Django 2.0.5 on 2018-05-18 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_stroop2score_stroop2stimulus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balloon',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='balloon',
            name='start_date',
        ),
    ]
