# Generated by Django 2.0.5 on 2018-06-26 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20180623_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearcherGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=20)),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Researcher')),
            ],
        ),
    ]
