# Generated by Django 2.0.5 on 2018-07-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_researchergame'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchergame',
            name='comment',
            field=models.TextField(default='happy', max_length=200),
            preserve_default=False,
        ),
    ]
