# Generated by Django 2.0.5 on 2018-07-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_researchergame_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balloon',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='balloon',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cardsortstimulus',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cardsortstimulus',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='digitnbackstimulus',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='digitnbackstimulus',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='gonogostimulus',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='gonogostimulus',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='imagenbackstimulus',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='imagenbackstimulus',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='stroop2stimulus',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='stroop2stimulus',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='stroopstimulus',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='stroopstimulus',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
