# Generated by Django 2.0.5 on 2018-07-07 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20180707_1645'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BehavGameScore',
            new_name='ResearcherGameScore',
        ),
    ]
