# Generated by Django 2.0.5 on 2018-07-09 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20180707_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearcherGameStimulus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rt', models.FloatField(default=-1.0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='researchergamescore',
            old_name='rt',
            new_name='accuracy',
        ),
        migrations.RenameField(
            model_name='researchergamescore',
            old_name='score',
            new_name='avg_rt',
        ),
        migrations.AddField(
            model_name='researchergamestimulus',
            name='rgs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.ResearcherGameScore'),
        ),
    ]
