# Generated by Django 2.0.5 on 2018-07-13 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_auto_20180709_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchergamescore',
            name='user',
        ),
    ]
