# Generated by Django 2.0.7 on 2018-07-26 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_remove_researchergamescore_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchergame',
            name='researcher',
        ),
        migrations.RemoveField(
            model_name='researchergamescore',
            name='researcher',
        ),
        migrations.RemoveField(
            model_name='researchergamestimulus',
            name='rgs',
        ),
        migrations.DeleteModel(
            name='Researcher',
        ),
        migrations.DeleteModel(
            name='ResearcherGame',
        ),
        migrations.DeleteModel(
            name='ResearcherGameScore',
        ),
        migrations.DeleteModel(
            name='ResearcherGameStimulus',
        ),
    ]
