# Generated by Django 2.0.7 on 2018-07-26 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('pw', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResearcherGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=20)),
                ('comment', models.TextField(max_length=200)),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researcher.Researcher')),
            ],
        ),
        migrations.CreateModel(
            name='ResearcherGameScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=20)),
                ('accuracy', models.FloatField(default=-1.0)),
                ('avg_rt', models.FloatField(default=-1.0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researcher.Researcher')),
            ],
        ),
        migrations.CreateModel(
            name='ResearcherGameStimulus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rt', models.FloatField(default=-1.0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('rgs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researcher.ResearcherGameScore')),
            ],
        ),
    ]
