# Generated by Django 2.1 on 2018-09-11 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcherexpstimulus',
            name='response',
            field=models.IntegerField(default=0),
        ),
    ]
