# Generated by Django 2.1.2 on 2018-10-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0002_researcherexpstimulus_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcherexp',
            name='kor_exp_name',
            field=models.CharField(default='기본 실험명', max_length=40),
        ),
    ]
