# Generated by Django 2.1 on 2018-10-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0003_researcherexp_kor_exp_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcherexpscore',
            name='gyro_mag',
            field=models.FloatField(default=-1.0),
        ),
    ]
